version: '3.9'

services:
  mydocker-api-dev:
    container_name: mydocker-api-dev
    image: mydocker-api/dev
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      - NODE_ENV=development
