version: '3.9'

services:
  api:
    container_name: api-local
    image: mydocker/api-local
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/src/app
      - /src/app/node_modules
    env_file:
      - .env.local
    command:
      - nodemon
      - --inspect=0.0.0.0:9229
      - server.js
